"use client";
import {useEffect,useState} from "react";

type User={username:string;progress:{seconds?:number;sessions?:number;daily?:Record<string,number>}};
function fmt(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}h ${m}m ${s}s`:`${m}m ${s}s`}

export default function Admin(){
 const [password,setPassword]=useState("");const [authed,setAuthed]=useState(false);const [error,setError]=useState("");const [users,setUsers]=useState<User[]>([]);const [busy,setBusy]=useState(false);const [values,setValues]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/admin",{cache:"no-store"});if(!r.ok){setAuthed(false);return}const x=await r.json();setUsers(x.users||[]);setAuthed(true);const next:Record<string,string>={};for(const u of x.users||[])next[u.username]=String(Math.floor(Number(u.progress?.seconds||0)/60));setValues(next)}
 useEffect(()=>{void load()},[]);
 async function login(){setBusy(true);setError("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(!r.ok){const x=await r.json().catch(()=>null);throw new Error(x?.error||"Login failed")}setPassword("");await load()}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}}
 async function save(username:string){setBusy(true);setError("");try{const minutes=Math.max(0,Math.floor(Number(values[username])));if(!Number.isFinite(minutes))throw new Error("Invalid time");const r=await fetch("/api/admin",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,seconds:minutes*60})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Update failed");await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setBusy(false)}}
 async function logout(){await fetch("/api/admin",{method:"DELETE"});setAuthed(false)}
 if(!authed)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24}}><section className="glass-panel" style={{width:"min(420px,100%)",padding:28}}><span className="section-kicker">STUDY X / ADMIN</span><h1>Admin panel</h1><p>Enter the admin password to manage stored study time.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" onKeyDown={e=>{if(e.key==="Enter")void login()}} style={{width:"100%",margin:"16px 0",padding:12}}/>{error&&<p>{error}</p>}<button className="login-primary" disabled={busy||!password} onClick={login}>{busy?"Checking…":"Open admin panel"}</button></section></main>;
 return <main style={{minHeight:"100vh",padding:"48px 24px",maxWidth:1000,margin:"0 auto"}}><div className="page-heading"><span className="section-kicker">STUDY X / ADMIN</span><h1>Admin panel</h1><p>Edit stored study time without changing the timer UI.</p></div>{error&&<p>{error}</p>}<button className="login-secondary" onClick={logout}>Sign out admin</button><section className="glass-panel" style={{marginTop:24,padding:20}}><h2>Users</h2>{users.length===0?<p>No stored progress users found.</p>:users.map(u=><div key={u.username} style={{display:"grid",gridTemplateColumns:"1fr 150px 90px",gap:12,alignItems:"center",padding:"14px 0",borderBottom:"1px solid rgba(255,255,255,.08)"}}><div><b>{u.username}</b><small style={{display:"block",opacity:.7}}>{fmt(Number(u.progress?.seconds||0))} stored · {Number(u.progress?.sessions||0)} sessions</small></div><input type="number" min="0" value={values[u.username]??"0"} onChange={e=>setValues(v=>({...v,[u.username]:e.target.value}))} aria-label={`${u.username} study minutes`}/><button className="login-primary" disabled={busy} onClick={()=>void save(u.username)}>Save</button></div>)}</section></main>;
}
