"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type User={username:string;progress:{seconds?:number;sessions?:number;daily?:Record<string,number>}};
function fmt(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}h ${m}m ${s}s`:`${m}m ${s}s`}

export default function Admin(){
 const [password,setPassword]=useState("");const [authed,setAuthed]=useState(false);const [error,setError]=useState("");const [users,setUsers]=useState<User[]>([]);const [busy,setBusy]=useState(false);const [values,setValues]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/admin",{cache:"no-store"});if(!r.ok){setAuthed(false);return}const x=await r.json();setUsers(x.users||[]);setAuthed(true);const next:Record<string,string>={};for(const u of x.users||[])next[u.username]=String(Math.floor(Number(u.progress?.seconds||0)/60));setValues(next)}
 useEffect(()=>{void load()},[]);
 async function login(){setBusy(true);setError("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(!r.ok){const x=await r.json().catch(()=>null);throw new Error(x?.error||"Login failed")}setPassword("");await load()}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}}
 async function save(username:string){setBusy(true);setError("");try{const minutes=Math.floor(Number(values[username]));if(!Number.isFinite(minutes)||minutes<0)throw new Error("Invalid time");const r=await fetch("/api/admin",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,seconds:minutes*60})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Update failed");await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setBusy(false)}}
 async function logout(){await fetch("/api/admin",{method:"DELETE"});setAuthed(false)}
 if(!authed)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:24,background:"radial-gradient(circle at top,rgba(255,255,255,.08),transparent 42%)"}}><section className="glass-panel" style={{width:"min(460px,100%)",padding:36,borderRadius:24,boxShadow:"0 24px 80px rgba(0,0,0,.35)"}}><span className="section-kicker">STUDY X / PRIVATE</span><h1 style={{marginBottom:8}}>Admin access</h1><p style={{opacity:.7,lineHeight:1.6}}>Private controls for managing stored study time.</p><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter admin password" onKeyDown={e=>{if(e.key==="Enter")void login()}} style={{width:"100%",margin:"20px 0 12px",padding:"14px 16px",borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.04)",color:"inherit"}}/>{error&&<p style={{margin:"8px 0 14px",opacity:.8}}>{error}</p>}<button className="login-primary" style={{width:"100%"}} disabled={busy||!password} onClick={login}>{busy?"Verifying…":"Enter admin panel"}</button><Link href="/" className="login-secondary" style={{display:"block",textAlign:"center",marginTop:10,textDecoration:"none"}}>Back to Study X</Link></section></main>;
 return <main style={{minHeight:"100vh",padding:"56px 24px 80px",maxWidth:1100,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:20,marginBottom:30}}><div className="page-heading" style={{margin:0}}><span className="section-kicker">STUDY X / PRIVATE ADMIN</span><h1>Control center</h1><p>Manage stored study time without touching the timer experience.</p></div><div style={{display:"flex",gap:10}}><Link href="/" className="login-secondary" style={{textDecoration:"none"}}>Study X</Link><button className="login-secondary" onClick={logout}>Sign out</button></div></div>{error&&<div className="glass-panel" style={{padding:"12px 16px",marginBottom:18}}>{error}</div>}<div className="stats-grid" style={{marginBottom:24}}><div className="stat-card"><span>01</span><b>{users.length}</b><small>Accounts</small></div><div className="stat-card"><span>02</span><b>{users.reduce((n,u)=>n+Number(u.progress?.seconds||0),0)>0?fmt(users.reduce((n,u)=>n+Number(u.progress?.seconds||0),0)):"0m"}</b><small>Total stored time</small></div><div className="stat-card"><span>03</span><b>{users.reduce((n,u)=>n+Number(u.progress?.sessions||0),0)}</b><small>Total sessions</small></div></div><section className="glass-panel" style={{padding:24,borderRadius:22}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div><span className="section-kicker">PROGRESS DATABASE</span><h2 style={{margin:"6px 0 0"}}>Study time</h2></div><span style={{opacity:.55,fontSize:12}}>MINUTES</span></div>{users.length===0?<p style={{opacity:.65}}>No stored progress users found.</p>:users.map(u=><div key={u.username} style={{display:"grid",gridTemplateColumns:"1fr minmax(120px,170px) 82px",gap:12,alignItems:"center",padding:"16px 0",borderBottom:"1px solid rgba(255,255,255,.07)"}}><div><b>{u.username}</b><small style={{display:"block",opacity:.55,marginTop:4}}>{fmt(Number(u.progress?.seconds||0))} stored · {Number(u.progress?.sessions||0)} sessions</small></div><input type="number" min="0" value={values[u.username]??"0"} onChange={e=>setValues(v=>({...v,[u.username]:e.target.value}))} aria-label={`${u.username} study minutes`} style={{padding:"11px 12px",borderRadius:10,border:"1px solid rgba(255,255,255,.1)",background:"rgba(255,255,255,.035)",color:"inherit"}}/><button className="login-primary" disabled={busy} onClick={()=>void save(u.username)}>Save</button></div>)}</section></main>;
}
