import {NextRequest,NextResponse} from "next/server";
import crypto from "crypto";
function secret(){return process.env.STUDY_X_AUTH_SECRET||"dev-only-change-me"}
function sign(v:string){return crypto.createHmac("sha256",secret()).update(v).digest("hex")}
function token(u:string){const p=Buffer.from(JSON.stringify({u,exp:Date.now()+2592000000})).toString("base64url");return p+"."+sign(p)}
function current(req:NextRequest){const t=req.cookies.get("study_x_session")?.value;if(!t)return null;const [p,s]=t.split(".");if(!p||s!==sign(p))return null;try{const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.exp>Date.now()?x.u:null}catch{return null}}
export async function POST(req:NextRequest){try{const {username,password}=await req.json();const envAccounts=JSON.parse(process.env.STUDY_X_ACCOUNTS||"[]") as {username:string,password:string}[]; const defaultAccounts=[{username:"RAJNIKANT07",password:"rajnikant07"},{username:"GULSHAN07",password:"gulshan07"},{username:"AMBAR07",password:"ambar07"}]; const accounts=envAccounts.length?envAccounts:defaultAccounts;const a=accounts.find(x=>x.username===String(username||"").trim()&&x.password===String(password||""));if(!a)return NextResponse.json({error:"Invalid username or password"},{status:401});const res=NextResponse.json({ok:true,username:a.username});res.cookies.set("study_x_session",token(a.username),{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:2592000});return res}catch{return NextResponse.json({error:"Login failed"},{status:400})}}
export async function GET(req:NextRequest){const u=current(req);return NextResponse.json({loggedIn:!!u,username:u})}
export async function DELETE(){const res=NextResponse.json({ok:true});res.cookies.set("study_x_session","",{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:0});return res}
