import {NextRequest,NextResponse} from "next/server";
import crypto from "crypto";

function secret(){return process.env.STUDY_X_AUTH_SECRET||"dev-only-change-me"}
function adminPassword(){return "8291"}
function sign(v:string){return crypto.createHmac("sha256",secret()).update(v).digest("hex")}
function makeAdminToken(){const p=Buffer.from(JSON.stringify({admin:true,exp:Date.now()+86400000})).toString("base64url");return p+"."+sign(p)}
function isAdmin(req:NextRequest){const t=req.cookies.get("study_x_admin")?.value;if(!t)return false;const [p,s]=t.split(".");if(!p||s!==sign(p))return false;try{const x=JSON.parse(Buffer.from(p,"base64url").toString());return x.admin===true&&x.exp>Date.now()}catch{return false}}
function redisConfig(){const url=process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL;const token=process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN;if(!url||!token)throw new Error("Cloud storage is not configured");return {url,token}}
async function kv(command:string[]){const {url,token}=redisConfig();const r=await fetch(url,{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(command),cache:"no-store"});if(!r.ok)throw new Error("Storage request failed");const json=await r.json();if(json.error)throw new Error(String(json.error));return json}
async function readJson(key:string,fallback:any){const r=await kv(["GET",key]);if(!r.result)return fallback;try{return JSON.parse(r.result)}catch{return fallback}}

export async function POST(req:NextRequest){try{const body=await req.json();if(String(body?.password||"")!==adminPassword())return NextResponse.json({error:"Invalid admin password"},{status:401});const res=NextResponse.json({ok:true});res.cookies.set("study_x_admin",makeAdminToken(),{httpOnly:true,secure:true,sameSite:"strict",path:"/",maxAge:86400});return res}catch{return NextResponse.json({error:"Admin login failed"},{status:400})}}

export async function GET(req:NextRequest){if(!isAdmin(req))return NextResponse.json({error:"Unauthorized"},{status:401});try{let cursor="0";const users=new Map<string,any>();do{const r=await kv(["SCAN",cursor,"MATCH","studyx:user:*:progress","COUNT","100"]);const result=Array.isArray(r.result)?r.result:["0",[]];cursor=String(result[0]||"0");for(const key of (Array.isArray(result[1])?result[1]:[])){const k=String(key),prefix="studyx:user:",suffix=":progress";if(!k.startsWith(prefix)||!k.endsWith(suffix))continue;const username=k.slice(prefix.length,-suffix.length);if(username&&!users.has(username))users.set(username,await readJson(k,{seconds:0,sessions:0,daily:{}}))}}while(cursor!=="0");const data=Array.from(users.entries()).map(([username,progress])=>({username,progress})).sort((a,b)=>a.username.localeCompare(b.username));return NextResponse.json({users:data})}catch{return NextResponse.json({error:"Cloud storage is not configured"},{status:503})}}

export async function PATCH(req:NextRequest){if(!isAdmin(req))return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await req.json();const username=String(body?.username||"").trim();if(!username)return NextResponse.json({error:"Username is required"},{status:400});const seconds=Math.floor(Number(body?.seconds));if(!Number.isFinite(seconds)||seconds<0)return NextResponse.json({error:"Invalid seconds"},{status:400});const current=await readJson("studyx:user:"+username+":progress",{seconds:0,sessions:0,daily:{}});const progress={...current,seconds,updatedAt:Date.now()};await kv(["SET","studyx:user:"+username+":progress",JSON.stringify(progress)]);const tasks=await readJson("studyx:user:"+username+":tasks",[]);await kv(["SET","studyx:user:"+username,JSON.stringify({progress,tasks})]);await kv(["ZADD","studyx:leaderboard",String(seconds),username]);return NextResponse.json({ok:true,username,progress})}catch{return NextResponse.json({error:"Could not update progress"},{status:500})}}

export async function DELETE(req:NextRequest){if(!isAdmin(req))return NextResponse.json({error:"Unauthorized"},{status:401});const res=NextResponse.json({ok:true});res.cookies.set("study_x_admin","",{httpOnly:true,secure:true,sameSite:"strict",path:"/",maxAge:0});return res}
